In [1]:
import numpy as np

In [2]:
arr_id = np.array([1,2,3,4])
print(arr_id)

[1 2 3 4]


In [3]:
type(arr_id)

numpy.ndarray

In [4]:
arr_id.ndim

1

In [5]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
arr_2d.ndim

2

In [7]:
arr_2d.size

8