In [1]:
import numpy as np

# Create a sample matrix
A = np.array([[3, 2, 2], 
              [2, 3, -2]])

# Perform SVD
U, S, Vt = np.linalg.svd(A)

# Display results
print("U matrix:\n", U)
print("Singular values:\n", S)
print("V transpose matrix:\n", Vt)

# Reconstructing the original matrix
Sigma = np.zeros((A.shape[0], A.shape[1]))
np.fill_diagonal(Sigma, S)

A_reconstructed = U @ Sigma @ Vt
print("\nReconstructed matrix:\n", A_reconstructed)


U matrix:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular values:
 [5. 3.]
V transpose matrix:
 [[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]

Reconstructed matrix:
 [[ 3.  2.  2.]
 [ 2.  3. -2.]]
