In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
type(arr_1d)

numpy.ndarray

In [4]:
arr_1d.ndim #tells dimesion of arr_1d

1

In [6]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr_2d.size

8